name: Sync Notion to Organization Readme

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch Notion Content
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        run: |
          pip install notion-client markdownify
          python3 <<'EOF'
          from notion_client import Client
          import os
          
          notion = Client(auth=os.environ["NOTION_TOKEN"])
          page = notion.blocks.children.list(block_id="2889f783227480539afffe3b5aa75005")
          
          def parse_block(block):
              t = block["type"]
              if t == "heading_1":
                  return "# " + "".join([r["plain_text"] for r in block[t]["rich_text"]]) + "\n\n"
              if t == "heading_2":
                  return "## " + "".join([r["plain_text"] for r in block[t]["rich_text"]]) + "\n\n"
              if t == "heading_3":
                  return "### " + "".join([r["plain_text"] for r in block[t]["rich_text"]]) + "\n\n"
              if t == "bulleted_list_item":
                  return "- " + "".join([r["plain_text"] for r in block[t]["rich_text"]]) + "\n"
              if t == "numbered_list_item":
                  return "1. " + "".join([r["plain_text"] for r in block[t]["rich_text"]]) + "\n"
              if t == "divider":
                  return "---\n\n"
              if t == "paragraph":
                  return "".join([r["plain_text"] for r in block[t]["rich_text"]]) + "\n\n"
              return ""
          
          content = "".join(parse_block(b) for b in page["results"])
          
          with open("README.md", "w", encoding="utf-8") as f:
            f.write(content)

          EOF

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "auto: sync from Notion" || echo "No changes"
          git push
