name: Sync Notion to Organization Readme

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch Notion Content
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        run: |
          pip install notion-client markdownify
          python3 <<'EOF'
          from notion_client import Client
          from markdownify import markdownify as md
          import os

          notion = Client(auth=os.environ["NOTION_TOKEN"])
          page = notion.blocks.children.list(block_id="2889f783227480539afffe3b5aa75005")

          content = []
          for block in page["results"]:
              if "paragraph" in block:
                  text = "".join([t["plain_text"] for t in block["paragraph"]["rich_text"]])
                  content.append(text)

          with open("README.md", "w", encoding="utf-8") as f:
              f.write("".join(content))
          EOF

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "auto: sync from Notion" || echo "No changes"
          git push
